language: es
pipeline:
- name: SpacyNLP
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 150
  random_seed: 1
- name: ResponseSelector
  epochs: 100
  random_seed: 1
  use_text_as_label: False
  retrieval_intent: faq
- name: ResponseSelector
  epochs: 100
  random_seed: 1
  use_text_as_label: False
  retrieval_intent: chitchat
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - time
  - number
  - duration
  locale: es_CO
  timezone: America/Guayaquil
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.7
  ambiguity_threshold: 0.1
policies:
- name: TEDPolicy
  max_history: 4
  epochs: 100
- name: AugmentedMemoizationPolicy
  max_history: 4
- name: RulePolicy
  core_fallback_threshold: 0.7
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: True
