# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "es"

# The two most important pipelines are supervised_embeddings and pretrained_embeddings_spacy.
# The biggest difference between them is that the pretrained_embeddings_spacy pipeline uses pre-trained word vectors from either GloVe
# or fastText. Instead, the supervised_embeddings pipeline doesn’t use any pre-trained word vectors, but instead fits
# these specifically for your dataset.


#pipeline: pretrained_embeddings_spacy
# pretrained_embeddings_spacy pipeline has the following structure
#
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "SpacyFeaturizer"
- name: "RegexFeaturizer"
- name: "CRFEntityExtractor"
- name: "SpacyEntityExtractor"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
# - max_history: This controls how much dialogue history the model looks at to decide which action to take next.
# - nlu-threshold: the fallback action or the utter_default will be executed if the intent recognition has a confidence
#   below a threshold (0-1). This value can be set based on NLU model evaluation results.
policies:
  - name: KerasPolicy
    epochs: 50
    max_history: 5
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.29
    core_threshold: 0.29
    fallback_action_name: "utter_default"