# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "es"

# The two most important pipelines are tensorflow_embedding and spacy_sklearn.
# The biggest difference between them is that the spacy_sklearn pipeline uses pre-trained word vectors from either GloVe
# or fastText. Instead, the tensorflow embedding pipeline doesn’t use any pre-trained word vectors, but instead fits
# these specifically for your dataset.
pipeline: pretrained_embeddings_spacy

# spacy_sklearn pipeline has the following structure
#
#pipeline:
#  - name: "nlp_spacy"
#  - name: "tokenizer_spacy"
#  - name: "intent_entity_featurizer_regex"
#  - name: "intent_featurizer_spacy"
#  - name: "ner_crf"
#  - name: "ner_synonyms"
#  - name: "intent_classifier_sklearn"

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
# - max_history: This controls how much dialogue history the model looks at to decide which action to take next.
# - nlu-threshold: the fallback action or the utter_default will be executed if the intent recognition has a confidence
#   below a threshold (0-1). This value can be set based on NLU model evaluation results.
policies:
  - name: KerasPolicy
    epochs: 50
    max_history: 5
  - name: MemoizationPolicy
    max_history: 5
  - name: FallbackPolicy
    nlu_threshold: 0.29
    core_threshold: 0.29
    fallback_action_name: "utter_default"