version: '3.4'

services:
  app:
    image: 'santteegt/glpi-chatbot-actions:latest'
    expose:
      - '5055'
    environment:
      GLPI_API_URI: "${GLPI_API_URI}"
      GLPI_APP_TOKEN: "${GLPI_APP_TOKEN}"
      GLPI_AUTH_TOKEN: "${GLPI_AUTH_TOKEN}"
      GLPI_LOCALMODE: "${GLPI_LOCALMODE}"
      USERS_API_BASE_URI: "${USERS_API_BASE_URI}"
      USERS_API_CLIENT_ID: "${USERS_API_CLIENT_ID}"
      USERS_API_CLIENT_SECRET: "${USERS_API_CLIENT_SECRET}"
    depends_on:
      - rasa-production
    extra_hosts:
      - "srvpruebas.ucuenca.edu.ec:172.16.0.44"
      - "cdsdesarrollo.ucuenca.edu.ec:172.16.1.76"