language: "es"

# The two most important pipelines are tensorflow_embedding and spacy_sklearn.
# The biggest difference between them is that the spacy_sklearn pipeline uses pre-trained word vectors from either GloVe
# or fastText. Instead, the tensorflow embedding pipeline doesn’t use any pre-trained word vectors, but instead fits
# these specifically for your dataset.
pipeline: spacy_sklearn

# spacy_sklearn pipeline has the following structure
#
#pipeline:
#  - name: "nlp_spacy"
#  - name: "tokenizer_spacy"
#  - name: "intent_entity_featurizer_regex"
#  - name: "intent_featurizer_spacy"
#  - name: "ner_crf"
#  - name: "ner_synonyms"
#  - name: "intent_classifier_sklearn"