name: Model CI
on:
  push:
    branches:
    - develop
    - master
    - rasa2
    paths-ignore:
    - "README.md"
    - "Makefile"
    - "Dockerfile"

jobs:
#  lint-testing:
#    name: Code Formatting Tests
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install -U pip
#        pip install -r requirements-dev.txt
#    - name: Code Formatting Tests
#      working-directory: ${{ github.workspace }}
#      run: |
#        make lint
#  type-testing:
#    name: Type Tests
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install -U pip
#        pip install -r requirements-dev.txt
#    - name: Type Checking
#      working-directory: ${{ github.workspace }}
#      run: |
#        make types
#  data-validation:
#    name: Rasa Data Validation
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.8
#    - name: Install dependencies
#      run: |
#        python -m pip install -U pip
#        pip install -r requirements-dev.txt
#        python -m spacy download es_core_news_md && python -m spacy link es_core_news_md es
#    - name: Rasa Data Validation
#      working-directory: ${{ github.workspace }}
#      run: |
#        make validate
  build-model:
    name: Build and test the model
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt
        python -m spacy download es_core_news_md && python -m spacy link es_core_news_md es
    - name: Test Training Stories
        working-directory: ${{ github.workspace }}
        run: |
          make test
