name: Model CI
on:
  push:
    branches:
    - 'develop'
    paths-ignore:
    - "README.md"
    - "Makefile"
    - "Dockerfile"

jobs:
#  lint-testing:
#    name: Code Formatting Tests
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python 3.7
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.7
#    - name: Install dependencies
#      run: |
#        python -m pip install -U pip
#        pip install -r requirements-dev.txt
#    - name: Code Formatting Tests
#      run: |
#        make formatter
#  type-testing:
#    name: Type Tests
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Set up Python 3.7
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.7
#    - name: Install dependencies
#      run: |
#        python -m pip install -U pip
#        pip install -r requirements-dev.txt
#    - name: Type Checking
#      working-directory: ${{ github.workspace }}
#      run: |
#        make types
  build-model:
    name: Build and test the model
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt

    - name: Rasa Data Validation
      run: |
        make validate

    - name: Train the model
      run: |
        rasa train

    - name: Run Through e2e Stories
      run: |
        make e2e

    - name: Cross-validate NLU model
      if: github.event_name == 'pull_request'
      run: |
        make crossval
